server:
  port: 8083
spring:
  application:
    name: gateway
  cloud:
    gateway:
      enabled: true
      routes:
        - id: provider
          uri: lb://provider
          predicates:
            - Path=/provider/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
eureka:
  client:
    service-url:
      defaulteZone: http://localhost:8761/euraka/
  instance:
    prefer-ip-address: true

