server:
  port: 8081
spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaulteZone: http://localhost:8761/euraka/
  instance:
    prefer-ip-address: true

management:
#  endpoint:
#    health:
#      show-details: always
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'

feign:
  hystrix:
    enabled: true