server:
  port: 8080
spring:
  application:
    name: provider
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: shouwang13
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC

logging:
  level:
    root: INFO
    # 配置日志级别，让hibernate打印出执行的SQL参数
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
eureka:
  client:
    service-url:
      defaulteZone: http://localhost:8761/euraka/
  instance:
    prefer-ip-address: true
